# fly.toml app configuration file generated for kronoz-cafe-bot on 2026-01-30T19:32:17+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kronoz-cafe-bot'
primary_region = 'jnb'

[build]

app = "kronoz-cafe-bot"

[http_service]
auto_stop_machines = false
auto_start_machines = false
min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
